### ISSUE TITLE
Running CodeClimateAnalyzeCurrentFile or CodeClimateAnalyzeOpenFiles isn't as limiting as I'd expect

### ISSUE THREAD

**Issue by jondkinney** [wfleming/vim-codeclimate#6]
Hi there,

Thanks very much for this plugin! I'm using it in Vim 7.4 inside Tmux (I don't think the tmux bit is particularly important, but I included it for full disclosure). When I run `:CodeClimateAnalyzeProject` (not via leader key as I haven't bound them yet), I predictably get all of the files analyzed, which is great. However, if I run either of the other two more focused commands I don't get the expected results.

With `:CodeClimateAnalyzeCurrentFile` items in the `gemfile.lock` are still found, as well as `routes.rb`. Perhaps those files are always analyzed no matter what by design? 

Similarly, when I run `:CodeClimateAnalyzeOpenFiles` and only have one file/buffer open, I still get results from `Gemfile.lock` and `routes.rb`

Any thoughts? 

Thanks!

**Comment by wfleming** [comment]
Hi @jondkinney,

Sorry for my delayed reply here. First guess here is that it sounds like maybe the versions of the engines you're using (I'm guessing maybe bundler-audit & brakeman based on the files you mentioned) aren't respecting the paths the Code Climate CLI is telling them to analyze. There's a couple things that would be helpful to narrow this down:
1. First, just to make sure this isn't a bug with this plugin, please run `codeclimate analyze some_file_in_in_your_project.rb` from a terminal, and see if that command also emits issues for `Gemfile.lock` and `routes.rb`. I expect that it will. If it does:
2. Please run `codeclimate engines:install` to ensure you have the latest versions of the engines you're using: it's possible there have been bugfixes to those engines that could fix this behavior.
3. Can you please confirm which engines are finding issues on `Gemfile.lock` & `routes.rb`? (The engine name is the text in brackets at the end of the line in the output after you run the analyze command.)

Thanks!

**Comment by wfleming** [comment]
Closing due to staleness.
